__version__: str
__author__: str
__copyright__: str
__email__: str
__description__: str
__date__: str
__contact__: str
__all_author__: list[str]
__license__: None  
__url__: None
__download_url__: None