from functools import total_ordering
from .core import _Bar

@total_ordering
class Bar(_Bar):
    def __init__(self, current: int =30, 
                 total: int=100, 
                 prefix: str="Progress",
                 width: int=30, 
                 fill_char: str="#", 
                 empty_char: str="-"): ...
    def _draw(self): ...
    def __repr__(self): ...
    def __hash__(self): ...
    def __eq__(self, value): ...
    def __gt__(self, other): ...
